### ISSUE TITLE
Create your own entangler for VQE

### ISSUE THREAD

**Issue by a-matsuo** [qiskit-community/qiskit-camp-asia-19#10]
# Abstract
Create your own entangler (or often called variational form) for VQE.

# Description 

Currently we have some entangler in Qiskit such as Ry, RyRz and swaprz.
However no one knows there are better entanglers or not.
VQE is a new method and we just started to do research.
There is a possibility we can find better entanglers.

**This project will be challenging. I have no idea how to implement my own entanglers. Definitly you need some programming knowledge.**

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by haoyudoingthings** [comment]
Hi, I'm currently learning about VQE and am interested in this topic. Do you have any specific details on this subject, or are you just throwing ideas around?

**Comment by a-matsuo** [comment]
Hi, I have some ideas for new entanglers, but I have no idea how to implement them into Qiskit Aqua yet. We need to search how we can implement entanglers into Qiskit Aqua before trying our own entanglers. The implementing part would be a challenging.
