### ISSUE TITLE
Measuring spread of quantum information via out-of-time ordered correlations

### ISSUE THREAD

**Issue by xkwei1119** [qiskit-community/qiskit-camp-asia-19#11]
# Abstract
How does quantum information move in a many-qubit system, and can we measure its dynamics in a quantum processor? Out-of-time ordered correlations (OTO) have been proposed as a tool for measuring spread of quantum information; it has been shown that OTO is a quantifier of quantum chaos [1].

# Description 
We will construct a simple quantum circuit to measure OTO, and demonstrate it experimentally on a real quantum device. OTO probes the buildup of many-qubit correlations. Consider the Pauli operator X_0 on qubit 0, under the evolution of a CNOT_01 gate, the operator X_0 is transformed into

X_0 -> CNOT_01 X_0 CNOT_01 = X_0 X_1

that is, X_0 has become correlated with X_1. Further applications of CNOT gates can generate N-body correlations: X_0 X_1 ...X_N-1. The extent of N-body correlations can be captured by OTO, which has the form

OTO = Tr(|[(CNOTs X_0 CNOTs, Z_j]|^2)

In our simple model OTO can be calculated exactly, it looks like
![image](https://user-images.githubusercontent.com/38588126/68512625-e91a4280-0246-11ea-8bad-188c079ebd37.png)
quantum information spreads like a light cone
![image](https://user-images.githubusercontent.com/38588126/68512746-3d252700-0247-11ea-80d5-13bd684f2c22.png)
Can we reproduce this result experimentally? How far does quantum information spread before it's destroyed by decoherence? What is the longest OTO correlation we can measure in our device?

additional challenge 1: implement many-qubit qiskit gates with the unitary in the form of e^{-i \phi XXX..XX}, currently only the 2-qubit version exists (rxx gate). 

additional challenge 2: implement the three-body H = P_0 X_1 P_2 interaction, where P = |0><0| is the projector onto the ground state. What is the least number CNOTs needed to implement this three-body interaction? This interaction can lead to many-body scars in strongly interacting Rydberg atoms.

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @xkwei1119 

# Deliverable
possibly a paper, qiskit demo, and module within qiskit

# GitHub repo

# References
[1] https://www.nature.com/articles/s41567-018-0295-5

**Comment by tehruhn** [comment]
Hi, @xkwei1119 , I would be extremely interested in working on this with you (I am a fellow Qiskit Camp invitee). Should we discuss details of this over email (in order to avoid spamming this issues thread, so that other interested people can message here as well)? Or you could personal-message me on Slack. I'm on the Qiskit Asia group, as Tarun Raheja.

**Comment by xkwei1119** [comment]
@tehruhn Hi Tarun, we can discuss here, so others who are interested can see as well.

**Comment by tehruhn** [comment]
Aah, okay. So what I wanted to talk about is relevant literature. I have more of a CS background than Physics, so I was wondering if you could recommend some background reading I could look at before the camp? I have very distributed knowledge in Physics, I know undergrad Quantum Mechanics, and I'm familiar with the Matrix Product States/DMRG formalism, and have done some work in Trotterization etc. , so would like to read up on the information theory stuff before camp.
Thanks in advance.

**Comment by xkwei1119** [comment]
Hi Tarun, yes there is a nice theory paper on various protocols to measure quantum information scrambling https://arxiv.org/abs/1602.06271 as well as the overview article I linked in the issue. A couple nice experimental demonstrations are in https://arxiv.org/abs/1608.08938 and https://arxiv.org/abs/1609.01246 We will hack something similar but will be simplified.

**Comment by starktech23** [comment]
Hi @xkwei1119 @tehruhn. I'm interested in contributing to the project at the camp as well. Thanks for the literature, will go through that.

**Comment by g-white** [comment]
Hey all, this sounds really interesting. Would love to discuss further at the camp :)

**Comment by starktech23** [comment]
I'm in. Samanvay Sharma, Computer Science.

**Comment by mf-22** [comment]
I'm in. Masahiro Fujii, Computer Science.
