### ISSUE TITLE
Making GPU statevector simulator portable (Qiskit Aer)

### ISSUE THREAD

**Issue by doichanj** [qiskit-community/qiskit-camp-asia-19#12]
# Abstract

Qiskit Aer will include GPU to accelerate simulation by using Thrust library that supports NVIDIA's GPUs. 
Because Thrust only supports NVIDIA's GPU, we have to implement with other libraries for the portability to other GPUs such as AMD's GPU or Intel's CPUs. 
In this activity we will consider how we can make the GPU simulator portable.

# Description 

We are now preparing for merging GPU implementation of statevector simulator of Qiskit Aer.
https://github.com/doichanj/qiskit-aer
This implementation uses Thrust C++ library (https://thrust.github.io/) that supports NVIDIA's GPUs. Thrust is a template library similar to STL, and by using Thrust library we can code without using CUDA or low level GPU APIs. However currently Thrust only supports NVIDIA's GPUs, so we have to consider to implement with other libraries that supports more GPUs for the portability.

In comparison to Thrust, Boost.Compute (https://github.com/boostorg/compute) is similar library that implies OpenCL. So Boost.compute is portable library supporting NVIDIA's GPUs, AMD's GPUs and Intel's CPUs (Intel HD Graphics).
Unfortunately, Power Systems with NVIDIA's GPUs (Power8 or Power9) do not support OpenCL and Boost.Compute is only portable on Intel based systems (Windows PC, Mac, x86 clusters).

Other candidate library is HIP (https://github.com/ROCm-Developer-Tools/HIP)
HIP is developed by AMD and the library is portable between AMD and NVIDIA.
HIP is used as replacement to CUDA, so if the code is written in CUDA it can be easily ported by HIP.
HIP is consist with low level API like CUDA, so it is less productive than Thrust or Boost.Compute.

# Members

 - 

 - Qiskit Coach: @doichanj  - Slack: `@doichan` 

# Deliverable

A report with feasibility study of libraries or implementation of portable GPU simulator.

# GitHub repo

https://github.com/doichanj/qiskit-aer/tree/portable

**Comment by chriseclectic** [comment]
There is also a AMD ROC Thrust library that might be useful for compiling existing Thrust code for AMD: https://github.com/ROCmSoftwarePlatform/Thrust

**Comment by doichanj** [comment]
So it seems GPU simulator written in Thrust is already portable.

**Comment by Brogis1** [comment]
Hi ! I am interested to talk to you anytime about the project ! I am at table 20 just in case.
