### ISSUE TITLE
[Qiskit-Aer] Improve qiskit-aer performance by rewriting a circuit

### ISSUE THREAD

**Issue by hhorii** [qiskit-community/qiskit-camp-asia-19#23]
# Abstract
Improve simulation performance in qiskit by adding specialized transpilation.

# Description 
There are two approaches to add new transpilation technique for simulation.

- [Add a pass in terra](https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/transpiler/passes)
- [Add a optimizer in aer](https://github.com/Qiskit/qiskit-aer/tree/master/src/transpile)

Some optimization candidates are: 

- Use [unitary-matrix-simulator](https://github.com/Qiskit/qiskit-aer/blob/master/src/simulators/unitary/unitary_controller.hpp) to generate a matrix for aggregated gates in [fusion.hpp](https://github.com/Qiskit/qiskit-aer/blob/master/src/transpile/fusion.hpp#L325-L365)
- Generate a large diagonal unitary matrix in terra or aer
- Enable `fusion_enable` optimization automatically depending on a number of qubits or circuit characteristics
- Reuse the same qubitvector to get samples for a circuit in noisy simulation

Benchmarks:

- [QFT](https://github.com/Qiskit/qiskit-terra/blob/master/examples/python/qft.py)
- [Quantum Volume](https://github.com/Qiskit/qiskit-aer/blob/master/test/benchmark/tools.py#L86-L123)

Setup of build environment:

- https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#install-from-source

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @hhorii  

# Deliverable

# GitHub repo

**Comment by hillmich** [comment]
Stefan Hillmich, CS

**Comment by kurarrr** [comment]
Ryota Yonekura, CS

**Comment by hhorii** [comment]
Merged to #6
