### ISSUE TITLE
Create a scheduled circuit transpiler pass

### ISSUE THREAD

**Issue by chriseclectic** [qiskit-community/qiskit-camp-asia-19#26]
# Abstract

Quantum circuits in Qiskit have no notion of gate times, pulse schedules on the other hand have an explicit structure for order of operations and their durations. This project would be to create an intermediate representation of a circuit that has the timing information used in pulse schedules, but without the pulse definitions themselves.

# Description 

Having an intermedate scheduled circuit with timing information would allow pulse scheduling to be implemented by first forming a scheduled circuit, and then simply mapping this circuit with a pulse definition. Additional transpiler passes could be implemented using the intermediate representation before the final pusle schedule is formed. 

Another important application would be implementing more accurate noise simulations for time-based noise effects such as T1/T2 relaxation and static Hamiltonian errors such as cross-talk. A stretch goal (or future work) based on this would be to implement time-based T1/T2 noise simulation in Qiskit Aer based on the timed circuit schedules.

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @chriseclectic 

# Deliverable

Terra transpiler pass

# GitHub repo

**Comment by mtreinish** [comment]
https://github.com/Qiskit/qiskit-terra/pull/3488 might be related to this
