### ISSUE TITLE
Good first issues

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-camp-asia-19#3]
# Abstract
Qiskit (Terra in particular) has [several bugs tagged as `good first issues`](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). These issues are low priority, relatively simple to fix, and they can be a good introduction the Qiskit codebase. This project is about closing as many of those issues as possible.
 
# Members
This project is a fallback to other projects. If you feel that you don't fit in any team, or your project come to a dead end before the hackathon finished, or you just want to improve your python/git/coding skills, then you are welcome here!
 
 - member
 - Qiskit Coach:
    - @1ucian0 - Slack: `@luciano`

# Deliverable
PRs! Mostly to https://github.com/Qiskit/qiskit-terra/pulls/

**Comment by boschmitt** [comment]
:)

**Comment by 1ucian0** [comment]
@qcamp join

**Comment by 1ucian0** [comment]
@qcamp join

**Comment by 1ucian0** [comment]
@qcamp join

**Comment by 1ucian0** [comment]
@qcamp join

**Comment by 1ucian0** [comment]
@qcamp join

**Comment by 1ucian0** [comment]
unrelated

**Comment by qcamp** [comment]
Hi @{self.participant.handler}! I could not add you to this group because you are already in #{current}. If you want to change teams, unassign yourself from #{self.group.number} and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #3 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its full.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its full.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its full.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its full.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its full.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its full.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #[1m#4[0m. If you want to change teams, unassign yourself from #[1m#4[0m and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because its closed.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by 1ucian0** [comment]
@qcamp

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by 1ucian0** [comment]
@qcamp

**Comment by 1ucian0** [comment]
@qcamp

**Comment by 1ucian0** [comment]
@qcamp

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because it is closed.

**Comment by 1ucian0** [comment]
@qcamp

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.
