### ISSUE TITLE
Create quantum state discriminator

### ISSUE THREAD

**Issue by nkanazawa1989** [qiskit-community/qiskit-camp-asia-19#34]
# Abstract

In OpenPulse framework, we support different types of quantum state readout format. Currently `level1` and `level2` measurements are available, and `level1` measurement returns raw integrated microwave signals in complex values (called IQ values) rather than conventional qubit state (0 or 1) - `level2`. Discriminator is a tool that converts those IQ values into qubit state, but official qiskit package only supports linear discriminant analysis. By utilizing some other advanced data analysis techniques (e.g. anomaly detection, radial basis function, etc...), is it possible to improve readout fidelity of measurement operations?

# Description 

IBMQ backends use dispersive readout technique, which yields difference in microwave signal distribution on IQ plane depending on the quantum state of measured qubit. You can see the actual distribution in the [Qiskit Ignis tutorial](https://github.com/Qiskit/qiskit-ignis/blob/master/examples/DiscriminatorTutorial.ipynb) or [qubit calibration tutorial](https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/ignis/1_calibrating_a_qubit.ipynb). Also you can refer to the [Qiskit/OpenPulse specification 5.2.4](https://arxiv.org/pdf/1809.03452.pdf) to find the details about discriminator. Detailed description of readout mechanism is available in [this paper](https://arxiv.org/abs/1411.4994). Campers having a background of physics or data science will be welcomed.

- classifying quantum state dependent distribution more accurately
- optimizing shape of measurement pulses to achieve higher fidelity
- providing a confidence of discriminated qubit state

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

- Adding new discriminator to Qiskit Ignis.

# GitHub repo

**Comment by masamuch** [comment]
I'm interested this project! I'm Masahiko Saito, Physicist.
