### ISSUE TITLE
Interactive Bloch sphere

### ISSUE THREAD

**Issue by Qr4cl3** [qiskit-community/qiskit-camp-asia-19#45]
# Abstract

The plot_bloch_sphere in Qiskit's visualization is hard to understand for people who new in the field of Quantum computing.
We have the idea that the interactive Bloch sphere in 3 dimensions should be easier to present the manipulation of Quantum gates to the Bloch vector. 
The animation of the Bloch sphere may be included.

![image](https://user-images.githubusercontent.com/6150928/69106465-03eb8300-0aa1-11ea-8305-b310a446a5a3.png)

# Description
We may use PyGame to implement the idea and connect to the Qiskit to perform a Quantum computation.

# Members
- visualization guys
- physicist 
- UX/UI design and frontend programmer.
 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 
 

# Deliverable
Application or library.

# GitHub repo

**Comment by rajchawit** [comment]
I'm Raj .. I'm in. and I'm Com Sci

**Comment by kifumi** [comment]
Hi, I'm in as a coach.
