### ISSUE TITLE
Solving Sudoku with Grover's Algorithm

### ISSUE THREAD

**Issue by yoooopeeee** [qiskit-community/qiskit-camp-asia-19#46]
# Abstract

Sudoku is a logic-based, combinatorial number-placement puzzle. The objective is to fill a 9×9 grid with digits so that each column, each row, and each of the nine 3×3 subgrids that compose the grid (also called "boxes", "blocks", or "regions") contain all of the digits from 1 to 9. 
In this project, we attempt to solve Sudoku efficiently with Grover's algorithm.

![image](https://user-images.githubusercontent.com/33653106/69106739-a3fdd800-0ab2-11ea-9fe1-40995eda0db9.png)

# Description 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @Ayumu-walker  

# Deliverable

- https://en.wikipedia.org/wiki/Sudoku
- https://github.com/quantum-challenge/2019/blob/master/problems/final/answer_and_comment_by_judges.ipynb
- https://newdoku.com/pdf/sudoku4100-ja.pdf

# GitHub repo

https://github.com/yoooopeeee/grover_sudoku/tree/master

**Comment by Keisuke-Kato-1107** [comment]
I'm Keisuke Kato

**Comment by zaki-joho** [comment]
I'm Hiroki Yamazaki.

**Comment by kentarotamura612** [comment]
Hello, my name is Kentaro Tamura, and I am a Master's student majoring in applied physics.
I'm interested in solving sudoku. May I join?

**Comment by Ayumu-walker** [comment]
I am Ayumu Shiraishi.

**Comment by zaki-joho** [comment]
link to the code we have been developing
https://github.com/yoooopeeee/grover_sudoku

**Comment by yoooopeeee** [comment]
[Solving Sudoku with Grover's Algorithm.pptx](https://github.com/qiskit-community/qiskit-camp-asia-19/files/3867934/Solving.Sudoku.with.Grover.s.Algorithm.pptx)
