### ISSUE TITLE
new Project name

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-camp-asia-19#51]
# Abstract

# Description 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by 1ucian0** [comment]
@qcamp

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #4. If you want to change teams, unassign yourself from #4 and write me again here.

**Comment by 1ucian0** [comment]
@qcamp

**Comment by 1ucian0** [comment]
@qcamp

**Comment by qcamp** [comment]
Hi @1ucian0! I could not add you to this group because you are already in #51. If you want to change teams, unassign yourself from #51 and write me again here.

**Comment by 1ucian0** [comment]
@qcamp
