### ISSUE TITLE
Solve optimization problems with a DOcplex translator

### ISSUE THREAD

**Issue by a-matsuo** [qiskit-community/qiskit-camp-asia-19#9]
# Abstract
Aqua has a DOcplex translator for optimization problems. It automatically generate an Ising Hamiltonian for an optimization problem from an optimization model to solve it with quantum computers. It is useful and new but there are not enough usage examples for the DOcplex translator.

# Description 

Solving an optimization problem with quantum computer requires translating the optimization problem into an Ising Hamiltonian, and then pass the Ising Hamiltonian to a quantum algorithm, such as Variational Quantum Eigensolver (VQE) algorithm and Quantum Approximate Optimization Algorithm (QAOA).  
[Qiskit Aqua: Experimenting with Max-Cut problem and Traveling Salesman problem with variational quantum eigensolver](https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/aqua/optimization/max_cut_and_tsp.ipynb)

A DOcplex translator can automatically generate Ising Hamiltonians from optimization models, so all user needs to do is to write models (Before the DOcplex translator, user needed to write translators of Ising Hamiltonians for each type of optimization problems manually. Writing translators is complicated and time-consuming tasks). It is useful and new but there are not enough usage examples for the DOcplex translator, so try the DOcplex translator and solve some optimization problems with it.
[Qiskit Aqua: Generating Ising Hamiltonians from optimization models with DOcplex](https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/aqua/optimization/docplex.ipynb)

**If you just try to use the DOcplex translator and conduct experiments. This project might be too easy. If so, you can enhance the DOcplex translator for additional functionality.**

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by zhou-wenbin** [comment]
Hi, I am Wenbin, doing quantum information theory for my Ph.D. Me and three others are interested in creating an ising model to optimize the financial market, to be specific, we want to create an ising model that minimizes a portfolio risk given the expected return through DOcplex translator. There are other ising model already in the qiskit finance, however our issue is different from them all.  
Reference:
1,Untangling complex networks: risk minimization in financial markets through accessible spin glass ground states (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2899695/)
2, https://github.com/Qiskit/qiskit-iqx-tutorials/tree/master/qiskit/advanced/aqua/finance
3,https://github.com/Qiskit/qiskit-community-tutorials/blob/master/awards/teach_me_qiskit_2018/exact_ising_model_simulation/Ising_time_evolution.ipynb?fbclid=IwAR10JN00282EqVENqy-q_wTNxyaxPfF4s8hV-j9UlNOkEM5-445ipweHX8M

**Comment by huan-yu-20** [comment]
Hi, I am in. My name is Huan-Yu Ku with room number 1303.

**Comment by tehruhn** [comment]
Hi, I am Tarun, and I am in as well (room number 1293).

**Comment by chiayiju** [comment]
Hi, I'm in. My name is Chia-Yi Ju. I'm a physicist.

**Comment by tehruhn** [comment]
I am considering moving to another project, and have unassigned myself.

**Comment by zhou-wenbin** [comment]
I am unassigned also
